const IT=[
{id:'wifi',i:'📶',t:'Wi-Fi indisponible',d:'Diagnostiquer une connexion qui ne fonctionne plus.',x:50,steps:['Vérifier si le Wi-Fi est activé.','Tester un autre appareil sur le même réseau.','Vérifier le routeur et les voyants.','Tester la connexion IP puis le DNS.']},
{id:'slow',i:'🐢',t:'PC très lent',d:'Trouver les causes courantes d’un poste ralenti.',x:60,steps:['Identifier depuis quand le problème existe.','Vérifier les applications ouvertes.','Contrôler l’espace disque et les ressources.','Redémarrer puis vérifier les mises à jour.']},
{id:'print',i:'🖨️',t:'Imprimante hors service',d:'Suivre une méthode de diagnostic utilisateur.',x:50,steps:['Vérifier alimentation et connexion.','Contrôler l’imprimante sélectionnée.','Vérifier la file d’impression.','Faire un test puis documenter le résultat.']},
{id:'account',i:'👤',t:'Compte utilisateur bloqué',d:'Apprendre le traitement sécurisé d’une demande.',x:55,steps:['Vérifier l’identité selon la procédure de l’organisation.','Identifier le message d’erreur.','Utiliser uniquement la procédure officielle de récupération.','Tracer l’intervention.']},
{id:'mail',i:'✉️',t:'E-mail non reçu',d:'Diagnostiquer une boîte mail sans modifier inutilement le compte.',x:55,steps:['Vérifier l’adresse du destinataire.','Chercher dans indésirables et archives.','Vérifier l’espace disponible.','Contrôler le statut du service.']},
{id:'update',i:'🔄',t:'Mise à jour qui échoue',d:'Analyser une erreur de mise à jour.',x:65,steps:['Lire le code d’erreur.','Vérifier réseau et espace disque.','Redémarrer si la procédure le prévoit.','Consulter la documentation officielle.']}
];
const CY=[
{id:'phish',i:'🎣',t:'Phishing',d:'Repérer une tentative de fraude par message.',x:60,steps:['Examiner l’expéditeur.','Vérifier l’adresse réelle du lien sans cliquer.','Repérer urgence, pression ou demande inhabituelle.','Signaler selon la procédure.']},
{id:'pass',i:'🔑',t:'Mots de passe & MFA',d:'Adopter de bonnes pratiques pour les comptes.',x:55,steps:['Un mot de passe par service.','Privilégier une phrase de passe longue.','Utiliser un gestionnaire reconnu si autorisé.','Activer la MFA quand elle est disponible.']},
{id:'device',i:'💻',t:'Poste compromis',d:'Réagir face à un comportement inhabituel.',x:75,steps:['Ne pas paniquer ni supprimer les traces.','Isoler le poste selon la procédure interne.','Prévenir le support ou responsable sécurité.','Documenter les symptômes et l’heure.']},
{id:'data',i:'🗂️',t:'Protection des données',d:'Identifier les informations qui doivent être protégées.',x:60,steps:['Limiter l’accès au besoin réel.','Éviter de partager des données sensibles inutilement.','Utiliser les espaces de stockage autorisés.','Signaler une perte ou exposition.']},
{id:'network',i:'🌐',t:'Sécurité réseau',d:'Comprendre pare-feu, ports et segmentation.',x:80,steps:['Identifier les flux nécessaires.','Comprendre le rôle d’un pare-feu.','Limiter les services exposés.','Surveiller les événements importants.']},
{id:'incident',i:'🚨',t:'Réponse à incident',d:'S’entraîner à qualifier et documenter un incident.',x:90,steps:['Qualifier le signalement.','Préserver les informations utiles.','Escalader au bon niveau.','Rédiger un compte rendu clair.']}
];
const Q={it:[['Un utilisateur n’a plus Internet. Quelle première étape est raisonnable ?',['Vérifier si le problème touche un seul appareil ou plusieurs','Réinstaller Windows immédiatement','Changer le mot de passe de l’utilisateur','Supprimer les pilotes au hasard'],0],['Un PC est lent. Que faut-il éviter ?',['Modifier des réglages au hasard sans diagnostic','Vérifier les ressources','Vérifier l’espace disque','Identifier les applications ouvertes'],0],['Une imprimante ne répond plus. Que vérifier d’abord ?',['Alimentation, connexion et imprimante sélectionnée','Changer toute la configuration réseau','Supprimer le compte utilisateur','Désinstaller tous les logiciels'],0]],cyber:[['Face à un e-mail suspect, quelle action est la plus sûre ?',['Vérifier l’expéditeur et le lien sans cliquer','Cliquer pour voir où il mène','Transférer le message à ses contacts','Répondre avec son mot de passe'],0],['Que signifie MFA ?',['Authentification multifacteur','Mémoire fichier automatique','Machine firewall active','Message filtré automatiquement'],0],['Lors d’un incident, pourquoi conserver les informations utiles ?',['Pour permettre l’analyse et le traitement de l’incident','Pour ralentir volontairement le système','Pour publier les logs','Pour supprimer les preuves'],0],['Quel est un bon réflexe pour les comptes ?',['Utiliser des mots de passe uniques et activer la MFA','Réutiliser le même mot de passe','Partager les codes','Désactiver les mises à jour'],0]],ai:[['Quel est le meilleur usage d’une IA pour le support ?',['Aider à expliquer ou structurer un diagnostic, puis vérifier les informations','Lui donner tous les mots de passe','La laisser modifier un système sans contrôle','Copier toutes les données sensibles'],0]]};
let S=JSON.parse(localStorage.getItem('supportAcademyState')||'null')||{name:'Utilisateur',done:[],xp:0,quiz:0,cquiz:0,qi:0,cqi:0,streak:0,last:null,theme:'dark',goal:15,activity:[],badges:[],daily:null};S={name:'Utilisateur',done:[],xp:0,quiz:0,cquiz:0,qi:0,cqi:0,streak:0,last:null,theme:'dark',goal:15,activity:[],badges:[],daily:null,...S};
const $=id=>document.getElementById(id),save=()=>localStorage.setItem('supportAcademyState',JSON.stringify(S)),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(x){const t=$('toast');t.textContent=x;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}function day(){return new Date().toISOString().slice(0,10)}function study(){const d=day();if(S.last===d)return;S.streak=S.last&&Math.round((new Date(d)-new Date(S.last))/86400000)===1?S.streak+1:1;S.last=d;save()}function all(){return[...IT,...CY]}function level(){const n=Math.floor(S.xp/100)+1;return[n,n<3?'Débutant':n<6?'Intermédiaire':n<10?'Avancé':'Expert',S.xp%100]}
function cards(a,id){$(id).innerHTML=a.map(c=>`<article class="card course"><div class="icon">${c.i}</div><span class="eyebrow">${c.x} XP · FORMATION</span><h3>${c.t}</h3><p>${c.d}</p><div class="course-foot"><span class="tag">${S.done.includes(c.id)?'✓ Terminé':'À faire'}</span><button class="primary" onclick="openCourse('${c.id}')">${S.done.includes(c.id)?'Revoir':'S’entraîner'}</button></div></article>`).join('')}
function render(){study();const A=all(),p=Math.round(S.done.length/A.length*100),L=level();$('xp').textContent=S.xp;$('level').textContent=`Niveau ${L[0]} · ${L[1]}`;$('progress').textContent=p+'%';$('progressBar').style.width=p+'%';$('bigProgress').textContent=p+'%';$('bigBar').style.width=p+'%';$('missions').textContent=S.done.length;$('streak').textContent=S.streak+' 🔥';$('name').value=S.name;$('goal').value=S.goal;cards(IT,'supportGrid');cards(CY,'cyberGrid');$('activity').innerHTML=S.activity.length?S.activity.slice(0,7).map(x=>`<p>• ${esc(x)}</p>`).join(''):'<p class="muted">Aucune activité pour le moment.</p>';const n=A.find(c=>!S.done.includes(c.id))||A[0];$('recommendTitle').textContent=n.t;$('recommendDesc').textContent=n.d;$('recommend').onclick=()=>openCourse(n.id);$('skills').innerHTML=A.map(c=>`<div class="skill"><span>${c.i} ${c.t}</span><div class="bar"><i style="width:${S.done.includes(c.id)?100:0}%"></i></div><small>${S.done.includes(c.id)?100:0}%</small></div>`).join('');const b=[['🎯','Première mission',S.done.length>=1],['🛠️','Support IT',S.done.some(x=>IT.some(c=>c.id===x))],['🔐','Cyber',S.done.some(x=>CY.some(c=>c.id===x))],['🧠','5 quiz',S.quiz+S.cquiz>=5],['🏆','100 XP',S.xp>=100],['🔥','3 jours',S.streak>=3]];$('badges').innerHTML=b.map(x=>`<div class="badge ${x[2]?'unlocked':''}"><span>${x[0]}</span><small>${x[1]}</small></div>`).join('');document.body.classList.toggle('light',S.theme==='light');document.body.classList.toggle('dark',S.theme==='dark')}
function section(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id==='progress'?'progressPage':id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='quiz')quiz();window.scrollTo({top:0,behavior:'smooth'})}
function openCourse(id){const c=all().find(x=>x.id===id);if(!c)return;const target=document.querySelector('.page.active');target.querySelectorAll('.module').forEach(x=>x.remove());const box=document.createElement('div');box.className='card module';box.innerHTML=`<span class="eyebrow">MISSION · ${c.x} XP</span><h2>${c.i} ${c.t}</h2><p>${c.d}</p><h3>Procédure d’entraînement</h3><div class="lesson-list">${c.steps.map((s,i)=>`<div class="lesson"><b>${i+1}</b><span>${esc(s)}</span></div>`).join('')}</div><p class="muted">Objectif : raisonner étape par étape et documenter ce que tu fais.</p><div class="module-actions"><button class="primary" id="finish">${S.done.includes(id)?'Mission déjà validée':'Valider la mission · +'+c.x+' XP'}</button><button class="secondary" id="back">← Retour</button></div>`;target.appendChild(box);$('finish').onclick=()=>finish(id);$('back').onclick=()=>{box.remove();render()};box.scrollIntoView({behavior:'smooth',block:'center'})}
function finish(id){const c=all().find(x=>x.id===id);if(!c||S.done.includes(id)){toast('Mission déjà validée.');return}S.done.push(id);S.xp+=c.x;S.activity.unshift(`Mission terminée : ${c.t} · +${c.x} XP`);S.activity=S.activity.slice(0,25);save();render();toast(`Mission validée · +${c.x} XP 🎯`)}
let mode='it',quizIndex=0;function quiz(){const a=Q[mode],idx=mode==='cyber'?S.cqi:S.qi,q=a[idx%a.length];$('quizBox').innerHTML=`<span class="eyebrow">${mode==='cyber'?'CYBERSÉCURITÉ':'SUPPORT IT'} · QUESTION ${idx%a.length+1}/${a.length}</span><p class="quiz-question">${q[0]}</p><div class="answers">${q[1].map((x,i)=>`<button class="answer" onclick="answerQuiz(${i})">${esc(x)}</button>`).join('')}</div><span class="tag">Score : ${S.quiz+S.cquiz}</span>`}function answerQuiz(i){const a=Q[mode],idx=mode==='cyber'?S.cqi:S.qi,q=a[idx%a.length];if(i===q[2]){mode==='cyber'?S.cquiz++:S.quiz++;S.xp+=25;S.activity.unshift('Quiz réussi · +25 XP');toast('Bonne réponse · +25 XP')}else toast('Réponse incorrecte · relis la notion');if(mode==='cyber')S.cqi++;else S.qi++;study();save();render();quiz()}
function daily(){if(S.daily===day()){toast('Défi déjà terminé aujourd’hui.');return}const q=Q.cyber[Math.floor(Math.random()*Q.cyber.length)];const box=document.createElement('div');box.className='card module';box.innerHTML=`<span class="eyebrow">DÉFI CYBER DU JOUR</span><h2>${q[0]}</h2><div class="answers">${q[1].map((x,i)=>`<button class="answer" data-i="${i}">${esc(x)}</button>`).join('')}</div>`;const page=document.querySelector('.page.active');page.appendChild(box);box.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)===q[2]){S.xp+=30;S.daily=day();S.activity.unshift('Défi cyber quotidien réussi · +30 XP');save();render();toast('Défi réussi · +30 XP 🏆')}else toast('Pas cette fois, réessaie demain.');box.remove()});box.scrollIntoView({behavior:'smooth',block:'center'})}
function lab(type){section('labs');const w=$('labBox');if(type==='phishing')w.innerHTML=`<span class="eyebrow">SIMULATION RÉALISTE · PHISHING</span><h2>🎣 Un utilisateur reçoit ce message</h2><div class="fake-message"><b>Support Microsoft</b><br>Votre session va expirer aujourd’hui. Vérifiez votre compte immédiatement via le lien ci-dessous.</div><div class="answers"><button class="answer" onclick="labAnswer(true)">Vérifier l’expéditeur et le lien sans cliquer</button><button class="answer" onclick="labAnswer(false)">Cliquer rapidement pour éviter le blocage</button></div><div id="labResult"></div>`;else w.innerHTML=`<span class="eyebrow">SIMULATION RÉALISTE · INCIDENT</span><h2>🚨 Poste utilisateur suspect</h2><p>Un utilisateur indique que des fenêtres inhabituelles apparaissent et que le poste agit bizarrement.</p><div class="alert-log">08:42 · Connexion inhabituelle détectée · poste TEST-07 · compte_demo</div><div class="answers"><button class="answer" onclick="labAnswer(true)">Suivre la procédure d’incident, isoler selon les règles et prévenir le support sécurité</button><button class="answer" onclick="labAnswer(false)">Supprimer les logs et continuer à utiliser le poste</button></div><div id="labResult"></div>`}function labAnswer(ok){$('labResult').innerHTML=ok?'<div class="lab-ok">✓ Bonne décision défensive · +15 XP</div>':'<div class="lab-bad">À revoir : ne supprime pas les traces et suis la procédure d’incident.</div>';if(ok){S.xp+=15;S.activity.unshift('Simulation cyber réussie · +15 XP');save();render()}}
function aiHelp(t){t=t.toLowerCase();if(t.includes('wifi')||t.includes('internet'))return'Commence par déterminer si le problème touche un seul appareil ou plusieurs. Vérifie ensuite Wi-Fi, connexion au routeur, puis IP/DNS. Évite de modifier des paramètres au hasard.';if(t.includes('phishing'))return'Ne clique pas. Vérifie l’expéditeur, l’adresse réelle du lien et le contexte, puis utilise la procédure de signalement de ton organisation.';if(t.includes('pc lent'))return'Commence par observer les ressources utilisées, les applications ouvertes, l’espace disque et les changements récents avant de modifier le système.';if(t.includes('incident'))return'Qualifie le signalement, conserve les informations utiles, suis la procédure interne et escalade au bon niveau.';return'Je peux t’aider à raisonner sur un incident support, réseau ou cybersécurité. Donne-moi le problème et ce qui a déjà été testé.'}
function init(){document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>section(n.dataset.page));$('startSupport').onclick=()=>section('support');$('startCyber').onclick=()=>section('cyber');$('daily').onclick=daily;$('theme').onclick=()=>{S.theme=S.theme==='dark'?'light':'dark';save();render()};$('profile').onclick=()=>section('settings');$('saveName').onclick=()=>{S.name=$('name').value.trim()||'Utilisateur';save();render();toast('Profil enregistré')};$('saveGoal').onclick=()=>{S.goal=Math.max(5,Math.min(180,Number($('goal').value)||15));save();toast('Objectif enregistré')};$('reset').onclick=()=>{if(confirm('Réinitialiser toute la progression ?')){const n=S.name;S={name:n,done:[],xp:0,quiz:0,cquiz:0,qi:0,cqi:0,streak:0,last:null,theme:S.theme,goal:S.goal,activity:[],badges:[],daily:null};save();render();toast('Progression réinitialisée')}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.q;quiz()});$('search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.course').forEach(c=>c.style.display=!q||c.textContent.toLowerCase().includes(q)?'':'none')};render();quiz()}init();