/* Assistant Vocal IA — mémoire cloud Supabase */
'use strict';
(function(){
  const cfg=window.TECHHELP_SUPABASE;
  if(!window.supabase||!cfg?.url||!cfg?.anonKey)return;
  const client=window.supabase.createClient(cfg.url,cfg.anonKey);
  window.VACloud={client};
  const keys=['va_reminders','va_events','va_notes','va_chat','va_theme','va_provider','va_model','va_ttsvoice'];
  let hydrating=false, timer;
  const read=()=>{const o={};for(const k of keys){const v=localStorage.getItem(k);if(v!==null){try{o[k]=JSON.parse(v)}catch{o[k]=v}}}return o};
  const set=(k,v)=>localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));
  function write(d){hydrating=true;for(const k of keys)if(d[k]!==undefined)set(k,d[k]);if(d.display_name)localStorage.setItem('va_profile_name',d.display_name);if(d.avatar_url)localStorage.setItem('va_avatar_url',d.avatar_url);hydrating=false;window.dispatchEvent(new Event('va-cloud-loaded'));}
  async function user(){return (await client.auth.getUser()).data.user||null;}
  async function saveCloud(){if(hydrating)return;const u=await user();if(!u)return;const d=read();await client.from('voice_assistant_data').upsert({user_id:u.id,reminders:d.va_reminders||[],events:d.va_events||[],notes:d.va_notes||[],chat:d.va_chat||[],theme:d.va_theme||'dark',provider:d.va_provider||null,model:d.va_model||null,ttsvoice:d.va_ttsvoice||null,display_name:localStorage.getItem('va_profile_name')||'Utilisateur',avatar_url:localStorage.getItem('va_avatar_url')||null,updated_at:new Date().toISOString()});}
  window.VACloud.save=()=>{clearTimeout(timer);timer=setTimeout(saveCloud,500)};
  async function loadFor(u){const {data,error}=await client.from('voice_assistant_data').select('*').eq('user_id',u.id).maybeSingle();if(error){console.warn(error);return}if(data)write({va_reminders:data.reminders,va_events:data.events,va_notes:data.notes,va_chat:data.chat,va_theme:data.theme,va_provider:data.provider,va_model:data.model,va_ttsvoice:data.ttsvoice,display_name:data.display_name,avatar_url:data.avatar_url});else await saveCloud();}
  function addAccountUI(){const view=document.getElementById('view-profile');if(!view||document.getElementById('vaAccount'))return;const box=document.createElement('div');box.id='vaAccount';box.className='card';box.style='padding:20px;margin-top:14px';box.innerHTML='<h3>☁️ Compte & mémoire permanente</h3><p class="muted" id="vaAuthStatus">Connexion cloud…</p><div id="vaAuthFields"><input id="vaEmail" class="wide-input" type="email" placeholder="Adresse e-mail" autocomplete="email"><input id="vaPassword" class="wide-input" type="password" placeholder="Mot de passe (6 caractères minimum)" autocomplete="new-password"><div class="map-actions"><button class="primary" id="vaSignUp">Créer mon compte</button><button class="secondary" id="vaSignIn">Se connecter</button></div></div><button class="secondary full" id="vaSignOut" style="display:none">Se déconnecter</button><small class="muted">Le mot de passe est géré par Supabase Auth et n’est jamais enregistré dans la mémoire de l’assistant.</small>';view.appendChild(box);document.getElementById('vaSignUp').onclick=async()=>{const email=document.getElementById('vaEmail').value.trim(),password=document.getElementById('vaPassword').value;if(password.length<6){setAuth('Mot de passe trop court.');return}setAuth('Création du compte…');const {error}=await client.auth.signUp({email,password});if(error)setAuth(error.message);else setAuth('Compte créé. Vérifie ton e-mail si une confirmation est demandée.');};document.getElementById('vaSignIn').onclick=async()=>{const email=document.getElementById('vaEmail').value.trim(),password=document.getElementById('vaPassword').value;setAuth('Connexion…');const {error}=await client.auth.signInWithPassword({email,password});if(error)setAuth(error.message);};document.getElementById('vaSignOut').onclick=()=>client.auth.signOut();}
  function setAuth(t){const x=document.getElementById('vaAuthStatus');if(x)x.textContent=t;}
  async function updateUI(){const u=await user();const fields=document.getElementById('vaAuthFields'),out=document.getElementById('vaSignOut');if(u){setAuth('☁️ Mémoire cloud active · '+(u.email||'compte invité'));if(fields)fields.style.display='none';if(out)out.style.display='block';const n=localStorage.getItem('va_profile_name');if(n&&document.getElementById('profileName'))document.getElementById('profileName').value=n;const a=localStorage.getItem('va_avatar_url');if(a&&document.getElementById('profileAvatarPreview'))document.getElementById('profileAvatarPreview').innerHTML='<img src="'+a+'" alt="Photo de profil" style="width:88px;height:88px;border-radius:50%;object-fit:cover">';}else{setAuth('🔒 Connecte-toi pour retrouver ta mémoire sur tous tes appareils.');if(fields)fields.style.display='block';if(out)out.style.display='none';}}
  async function uploadAvatar(file,u){if(!file||!file.type.startsWith('image/')||file.size>8*1024*1024)return null;const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').slice(0,5)||'jpg';const path=u.id+'/avatar.'+ext;const {error}=await client.storage.from('voice-avatars').upload(path,file,{upsert:true,contentType:file.type});if(error){setAuth('Impossible d’enregistrer la photo : '+error.message);return null}return client.storage.from('voice-avatars').getPublicUrl(path).data.publicUrl;}
  async function saveProfile(){const u=await user();if(!u)return setAuth('Connecte-toi d’abord.');const name=(document.getElementById('profileName')?.value||'Utilisateur').trim()||'Utilisateur';const file=document.getElementById('profileAvatar')?.files?.[0];let avatar=localStorage.getItem('va_avatar_url')||null;if(file){avatar=await uploadAvatar(file,u);if(!avatar)return}localStorage.setItem('va_profile_name',name);if(avatar)localStorage.setItem('va_avatar_url',avatar);await saveCloud();updateUI();setAuth('✅ Profil et mémoire enregistrés dans le cloud.');}
  function hookStorage(){const oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){oldSet.call(this,k,v);if(keys.includes(k)&&!hydrating)window.VACloud?.save?.()};}
  client.auth.onAuthStateChange((event,session)=>{if(session){setTimeout(async()=>{await loadFor(session.user);updateUI()},0)}else updateUI()});
  async function boot(){addAccountUI();hookStorage();const {data:{session}}=await client.auth.getSession();if(session){await loadFor(session.user)}else{try{const r=await client.auth.signInAnonymously();if(r.data?.session)await loadFor(r.data.session.user)}catch{}}updateUI();}
  document.addEventListener('click',e=>{if(e.target?.id==='saveProfile')saveProfile()});
  window.addEventListener('va-cloud-loaded',updateUI);
  boot();
})();
