services:
  - type: web
    name: ia-app-proxy
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: MISTRAL_API_KEY
        sync: false